### ISSUE TITLE
Iterative creation/use of cohort gvcf files

### ISSUE THREAD

**Issue by vrennie** [TORCH-Consortium/MAGMA#157]
We have previously explored this when we were running out of space on our cluster at UAntwerp.

The idea is that the pipeline could automatically use the previously generated cohort gvcfs when running new samples that belong to the same cohort.

This would allow health care institutions continually update their cluster and phylogenetic trees without extensive data storage infrastructure or waiting for the analysis of the entire cohort to re-run.

@abhi18av is there some way to program in nextflow where this file is so it can grab it each time?

@LennertVerboven @TimHHH I believe you mentioned that we already create this file, do you know exactly which one it is?

**Comment by abhi18av** [comment]
As of now those are limited only to EXIT-RIF files 

https://github.com/TORCH-Consortium/MAGMA/blob/master/default_params.config#L22-L23

Is the intention to generalize this parameter?

**Comment by vrennie** [comment]
Yes indeed the intention is to generalise. 

For example, Sciensano, the organisation largely responsible for TB control in Belgium, has a dataset of 3000 genomes which they have sequenced. This should be analysed and subsequently added to the EXIT-RIF dataset.

This is also related to the data management, as the idea is that this Sciensano + EXIT-RIF gvcf should be updated each time they analyse a new batch of samples, thus allowing them to add to their cohort phylogenetic tree without keeping the volume-heavy BAM files.

Any idea of the best mechanism or logic to achieve this?

**Comment by TimHHH** [comment]
This is doable, the functionality of the EXIT-RIF inclusion could be copied so that users can provide their own dataset instead.

This additional data is included at the [GATK_COMBINE_GVCFS](https://github.com/TORCH-Consortium/MAGMA/blob/master/workflows/subworkflows/prepare_cohort_vcf.nf) step; you can specify individual sample or cohort GVCF files at this stage for inclusion, the file paths need to be listed and separated with spaces. You need to supply the (unfiltered) GVCF found in ```/samples/variant_files/major_variants/haplotype_caller/``` or the combined GVCF. The latter is currently not published and should be turned on here: https://github.com/TORCH-Consortium/MAGMA/blob/master/default_params.config#L330-L336

In this form the whole process is fairly straight forward in terms of implementation and usage, but probably not recommended for your average user.

Do note that you will get the same limited output for the additional data as for EXIT-RIF. This means you won't get the summary stats or the TBprofiler analysis.
