### ISSUE TITLE
Magma via Conda Env

### ISSUE THREAD

**Issue by foamy1881** [TORCH-Consortium/MAGMA#186]
I'm new to this community and could use some help. How exactly does one execute Magma after installing it through Conda? I've followed the instructions and installed both magma-env-1 and magma-env-2. However, I'm at a loss regarding the next steps, specifically how to incorporate the sample sheet and execute the YAML file. Could anyone offer some guidance?

**Comment by abhi18av** [comment]
Hi @foamy1881 , thank you for your interest in the pipeline!


As this is not a feature/bug report, I am converting this into a discussion and will respond to these questions in a point-wise manner

### Point-1

> I've followed the instructions and installed both magma-env-1 and magma-env-2 

This sounds good 👍 

The next step here, I'd recommend you to do is to make sure that the WHO resistance catalog for tb-profiler has been loaded (I realized we didn't document this on Readme, I'll fix this).


**NOTE**: Basically the [instructions](https://github.com/TORCH-Consortium/MAGMA/blob/master/conda_envs/setup_conda_envs.sh#L20-L23), which are used to build the necessary docker containers. 

⚠️  We do highly recommend usage of the containers wherever possible 🐳 


1. Download [magma_resistance_db_who_v1.zip](https://github.com/TORCH-Consortium/MAGMA/files/14559680/resistance_db_who_v1.zip)  and unzip it

```console
wget https://github.com/TORCH-Consortium/MAGMA/files/14559680/resistance_db_who_v1.zip

unzip resistance_db_who

```

2. Activate `magma-env-1`, which has `tb-profiler`

```console
conda activate magma-env-1

```

3. Move inside that folder and use `tb-profiler load_library` functionality to load the database


```console

cd resistance_db_who

tb-profiler load_library ./resistance_db_who

```

Success, would look like this
<img width="1060" alt="image" src="https://github.com/TORCH-Consortium/MAGMA/assets/12799326/de5eb0fc-c636-44f6-a787-39bbbf8bc8c7">

 
### Point-2

> ... how to incorporate the sample sheet ...

For this, we provide a dummy samplesheet, which you'd have to customize as per your samples and other metadata from the sequencer and sample.



Reference: Mentioned on the readme [here](https://github.com/TORCH-Consortium/MAGMA?tab=readme-ov-file#samplesheet).

Below is a formatted version of that sample CSV.


|Study     |Sample|Library|Attempt|R1                                                        |R2                                                        |Flowcell|Lane|Index Sequence|
|----------|------|-------|-------|----------------------------------------------------------|----------------------------------------------------------|--------|----|--------------|
|Study_Name|S0001 |1      |1      |full_path_to_directory_of_fastq_files/S0001_01_R1.fastq.gz|full_path_to_directory_of_fastq_files/S0001_01_R1.fastq.gz|1       |1   |1             |
|Study_Name|S0002 |1      |1      |full_path_to_directory_of_fastq_files/S0002_01_R1.fastq.gz|full_path_to_directory_of_fastq_files/S0002_01_R2.fastq.gz|1       |1   |1             |
|Study_Name|S0003 |1      |1      |full_path_to_directory_of_fastq_files/S0003_01_R1.fastq.gz|full_path_to_directory_of_fastq_files/S0003_01_R2.fastq.gz|1       |1   |1             |
|Study_Name|S0004 |1      |1      |full_path_to_directory_of_fastq_files/S0004_01_R1.fastq.gz|full_path_to_directory_of_fastq_files/S0004_01_R2.fastq.gz|1       |1   |1             |



### Point-3 

> ... execute the YAML file


Actually the `YAML` is a condensed form of all inputs to the pipeline, therefore, you can pass/give it to the pipeline rather than `execute` in this case.

This information is covered [here](https://github.com/TORCH-Consortium/MAGMA?tab=readme-ov-file#customization) on Readme.
